/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import sistemaPetShop.*;
/**
 *
 * @author andre
 */
public class VenderProduto extends javax.swing.JFrame {
    
    private javax.swing.JFrame tela_anterior;
    private Loja loja;
    /**
     * Creates new form Vender
     */
    public VenderProduto() {
        initComponents();
    }
    public VenderProduto(javax.swing.JFrame tela_anterior, Loja loja){
        this();
        this.tela_anterior = tela_anterior;
        this.loja = loja;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lista_animais = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lista_produto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        quantidade_disponivel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valor_final = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        preco_produto = new javax.swing.JLabel();
        quantidades_disp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENDER PRODUTO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Animal :");

        lista_animais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lista_animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_animaisActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto");

        lista_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_produtoActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade diponível :");

        quantidade_disponivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidade_disponivel.setText("-");

        jLabel4.setText("Quantidade desejada: ");

        jLabel5.setText("Valor da compra: ");

        valor_final.setText("R$  0,00");

        jButton1.setText("Finalizar compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Preço :");

        preco_produto.setText("R$   0,00");

        quantidades_disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidades_dispActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valor_final)
                                .addGap(73, 73, 73))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lista_produto, 0, 118, Short.MAX_VALUE)
                                    .addComponent(lista_animais, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantidades_disp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantidade_disponivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(preco_produto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lista_animais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lista_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(preco_produto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantidade_disponivel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quantidades_disp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valor_final))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.tela_anterior.setEnabled(false);
        this.tela_anterior.setVisible(false);
                
        lista_animais.setModel(new javax.swing.DefaultComboBoxModel<>(loja.getAnimais()));
    }//GEN-LAST:event_formWindowOpened

    private void lista_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_produtoActionPerformed
        // TODO add your handling code here:
        // Ao selecionar produto
        String produto_selecionado = lista_produto.getSelectedItem().toString();
        String animal_selecionado = lista_animais.getSelectedItem().toString();
        Produto p = loja.getProduto(produto_selecionado, animal_selecionado);
        quantidade_disponivel.setText(String.valueOf(p.getQuantidade()));
        preco_produto.setText("R$" + String.format(" %.2f",p.getPreco()));
        int qtd = p.getQuantidade();// qtd do produto disponivel
        String quantias[] = new String[qtd];
        for(int i = 0; i < qtd; i++){
            quantias[i] = String.valueOf(i+1);
        }
        quantidades_disp.setModel(new javax.swing.DefaultComboBoxModel<>(quantias));
    }//GEN-LAST:event_lista_produtoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.tela_anterior.setEnabled(true);
        this.tela_anterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void lista_animaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_animaisActionPerformed
        // TODO add your handling code here:
        // AO SELECIONAR ANIMAL
        String animal_selecionado = lista_animais.getSelectedItem().toString();
        lista_produto.setModel(new javax.swing.DefaultComboBoxModel<>(loja.getProdutosDisp(animal_selecionado))); 

    }//GEN-LAST:event_lista_animaisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int qtd = Integer.valueOf(quantidades_disp.getSelectedItem().toString());
        String animal = String.valueOf(lista_animais.getSelectedItem());
        String produto = lista_produto.getSelectedItem().toString();
        loja.getProduto(produto, animal).setQuantidade(-qtd);
        loja.setControle("Vendeu-se " + qtd + " unidades de " + produto + " de " + animal + ", valor :" + valor_final.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quantidades_dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidades_dispActionPerformed
        // TODO add your handling code here:
        String animal = String.valueOf(lista_animais.getSelectedItem());
        String produto = lista_produto.getSelectedItem().toString();
        double valor_final1 = Integer.valueOf(quantidades_disp.getSelectedItem().toString()) * loja.getProduto(produto, animal).getPreco();//trocar para valor do produto
        
        valor_final.setText("R$" + String.format(" %.2f",valor_final1));
 
    }//GEN-LAST:event_quantidades_dispActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lista_animais;
    private javax.swing.JComboBox<String> lista_produto;
    private javax.swing.JLabel preco_produto;
    private javax.swing.JLabel quantidade_disponivel;
    private javax.swing.JComboBox<String> quantidades_disp;
    private javax.swing.JLabel valor_final;
    // End of variables declaration//GEN-END:variables
}
